add how to set up ubuntu OwnCloud and AWS Basic
Yoshiki217/Linux_prctice pull request #19
Opened 2024-11-19 04:56 UTC by Hegimu

organize 20241119 lectures

2024-11-21 10:47 UTC, Yoshiki217 requested changes

2024-11-21 10:47 UTC, Yoshiki217 commented on 202411/241119.md
> +- API Gateway : クラウドの木戸番
木戸番ってなんだｗ

2024-11-22 00:27 UTC, Hegimu commented on 202411/241119.md
> +- API Gateway : クラウドの木戸番
門を守る人って意味です

2024-11-22 12:27 UTC, Yoshiki217 commented on 202411/241119.md
> +- API Gateway : クラウドの木戸番
そうなんだしらなんだｗ

2024-11-22 12:27 UTC, Yoshiki217 commented
LGMT

2024-11-22 12:27 UTC, merged