setting_pic_drawio_directories
Yoshiki217/Linux_prctice pull request #7
Opened 2024-10-28 13:11 UTC by Hegimu

i am not idoit

2024-10-28 23:58 UTC, Hegimu commented
This branch has conflicts らしいです　たすけてください

2024-10-29 07:07 UTC, Yoshiki217 requested changes

2024-10-29 07:07 UTC, Yoshiki217 commented on 202410/28.md
> +hosts파일 -> localDNS
hosts に関してのメモなのはわかえるけど
configファイルのサンプルまで書いたほうがいい
```
192.168.0. example.com
```
など

2024-10-29 07:07 UTC, Yoshiki217 commented on 202410/28.md
> +Client -> yahoo.com どこですか
こちらも、resolv.confの書式に当たってconfigのサンプルを書くといいかも
あとからみてもわからない挙動に関してはざっくり理解していそうなので触れないでおきます
```
nameserver 8.8.8.8
```
上記サンプル
参照 blog : https://qiita.com/kasei-san/items/137b7fc86a0eacd60765

2024-10-29 07:08 UTC, Yoshiki217 commented
二点ほど指摘しています。
configファイルの場合はsample codeもしかくは
書式について書いておくと後々わかりやすいです

メモだけど、未来の自分がメモをみてわかるないようにすることを意識しましょう
再度修正してかrcommit をお願いします！！！！！！！

2024-10-29 08:01 UTC, Hegimu commented
指摘したところ修正してみました。ついでに内容も自分なりに少しわかりやすくしてみました
確認お願いします＾＾

2024-10-29 08:11 UTC, Yoshiki217 commented
いい感じにわかりやすくなってたのでOKです

2024-10-29 08:11 UTC, merged