add todayscommands
Yoshiki217/Linux_prctice pull request #9
Opened 2024-10-29 08:47 UTC by Hegimu

今日学んだコマンドをまとめておきました

2024-10-29 09:13 UTC, Yoshiki217 commented
NICE~~~~~~~

権限回りの違和感があるとおもうんだけど
rwx 4,2,1で表現してるけどなぜか、権限はなぜか8進数表記なのか
結論としては権限が3ビットで表現されるためです。

Linuxのファイル権限は、オーナー、グループ、その他のユーザーにそれぞれ3つの権限（読み取り、書き込み、実行）を持ちます。この3つの権限をビットで表すと、各権限は次のように定義されます：

読み取り（r）: 4（2^2）
書き込み（w）: 2（2^1）
実行（x）: 1（2^0）
したがって、オーナー、グループ、その他のユーザーの権限を合わせて3ビット×3=9ビットになります。8進数は、3ビット（0から7の範囲）の数値を1桁で表すのに最適である。

2024-10-29 09:14 UTC, Yoshiki217 commented
コメントは書いたけど、reviewが必要な場合はreview requestをお願いします

2024-10-30 08:16 UTC, Hegimu commented
今日のコマンドで、tarファイル作るのって日本語でなんっていうんですか？
韓国はファイル圧縮(xz,bz2)とファイルまとめ(tar)っていいます

2024-10-30 10:55 UTC, Yoshiki217 requested changes
根本的なmissはなかったです
たぶんあいまいな解説だったかふわっと触れられる程度のものだったかなという印象
そのだけ突っ込んでいます

2024-10-30 10:55 UTC, Yoshiki217 commented on 202410/30.md
> +#### ファイル圧縮、まとめ？ tarファイル作るのって日本でなんっていうの
ファイル圧縮という言い方が多いかな
基本的には
tar日本語だと"ター"なので意味わからん感じで伝わる

2024-10-30 10:55 UTC, Yoshiki217 commented on 202410/30.md
> +ただのtarファイルにするより、tarファイルにして、圧縮するほうがより容量的に小さくなる。
日本語的には意味が分からなくなっちゃうので
以下のような文面のほうがいいかとおもいます
```
圧縮する場合複数の圧縮方法がレベル別で存在しているので、圧縮する場合は圧縮効率を考えて
えらぶとよい
```

参考url : https://qiita.com/saoyagi2/items/59338616a2ca46d81dc2

2024-10-30 14:37 UTC, Hegimu commented
簡単に不自然なところとメモっていたところだけ修正しました

2024-10-31 05:20 UTC, Yoshiki217 commented
修正部分okだった

2024-10-31 05:20 UTC, merged